-- 02_BO_05_objects.sql
-- Fichier objects du TP2 modifié un peu

/*********** *SÉQUENCES *****************/
CREATE SEQUENCE bo.code_membre_seq
START WITH 5
INCREMENT BY 5
MAXVALUE 10000
NOCYCLE
NOCACHE;


/*********** TABLES *****************/

--------------------------------------------------------
--  DDL for Table SECTIONS
--------------------------------------------------------
CREATE TABLE bo.SECTIONS(
    ID NUMBER(3) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOM VARCHAR2(100 BYTE) NOT NULL,
    DESCRIPTION VARCHAR2(255 BYTE)
);

COMMENT ON TABLE bo.SECTIONS IS 'Table qui contient les différentes sections';

--------------------------------------------------------
--  DDL for Table GENRES
--------------------------------------------------------
CREATE TABLE bo.GENRES(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOM_GENRE VARCHAR2(50 BYTE) NOT NULL
);

COMMENT ON TABLE bo.GENRES IS 'Table qui contient les genres littéraires';

--------------------------------------------------------
--  DDL for Table AUTEURS
--------------------------------------------------------
CREATE TABLE bo.AUTEURS(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOM_AUTEUR VARCHAR2(100 BYTE) NOT NULL
);

COMMENT ON TABLE bo.AUTEURS IS 'Table qui contient la liste des auteurs';

--------------------------------------------------------
--  DDL for Table MEMBRES
--------------------------------------------------------
CREATE TABLE bo.MEMBRES(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CODE CHAR(12 CHAR) DEFAULT 'BOQC00000000' NOT NULL,
    PRENOM VARCHAR2(50 BYTE) NOT NULL,
    NOM VARCHAR2(50 BYTE) NOT NULL,
    GENRE CHAR(1),
    DATE_NAISSANCE DATE,
    COURRIEL VARCHAR2(50 BYTE) NOT NULL,
    ADRESSE_LIGNE1 VARCHAR2(50 BYTE),
    ADRESSE_LIGNE2 VARCHAR2(50 BYTE),
    VILLE VARCHAR2(50 BYTE) DEFAULT 'Québec',
    PROVINCE VARCHAR2(50 BYTE) DEFAULT 'Québec',
    CODE_POSTAL VARCHAR2(50 BYTE),
    PAYS VARCHAR2(50 BYTE) DEFAULT 'Canada',
    TELEPHONE VARCHAR2(50 BYTE),
    DATE_DEBUT_MEMBRE DATE,
    STATUT_MEMBRE VARCHAR2(15 BYTE),
    THEME_PREFERE VARCHAR2(15 BYTE)
);

COMMENT ON TABLE bo.MEMBRES IS 'Table qui contient les informations personnelles des membres.';

--------------------------------------------------------
--  DDL for Table LIVRES
--------------------------------------------------------
CREATE TABLE bo.LIVRES(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    SECTIONS_ID NUMBER(3) NOT NULL,
    AUTEURS_ID NUMBER NOT NULL,
    GENRES_ID NUMBER NOT NULL,
    ISBN VARCHAR2(50 BYTE) NOT NULL,
    TITRE VARCHAR2(50 BYTE) NOT NULL,
    MAISON_EDITION VARCHAR2(50 BYTE),
    ANNEE_PUBLICATION NUMBER(4),
    LANGAGE VARCHAR2(50 BYTE),
    PRIX NUMBER(5,2)
);

COMMENT ON TABLE bo.LIVRES IS 'Table qui contient les informations des livres.';


--------------------------------------------------------
--  DDL for Table EMPRUNTS
--------------------------------------------------------
CREATE TABLE bo.EMPRUNTS(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    LIVRES_ID NUMBER NOT NULL,
    MEMBRES_ID NUMBER NOT NULL,
    DATE_EMPRUNT DATE NOT NULL,
    DATE_RETOUR DATE
);

COMMENT ON TABLE bo.EMPRUNTS IS 'Table qui contient l''historique des emprunts effectués par les membres.';
COMMENT ON COLUMN bo.EMPRUNTS.ID IS 'ID de l''emprunt';
COMMENT ON COLUMN bo.EMPRUNTS.LIVRES_ID IS 'Référence vers le livre emprunté';
COMMENT ON COLUMN bo.EMPRUNTS.MEMBRES_ID IS 'Référence vers le membre qui a emprunté le livre';
COMMENT ON COLUMN bo.EMPRUNTS.DATE_EMPRUNT IS 'Date que le livre a été emprunté';
COMMENT ON COLUMN bo.EMPRUNTS.DATE_RETOUR IS 'Date de retour du livre';


/***************** INDEX ************************/

--------------------------------------------------------
--  Index pour la table MEMBRES
--------------------------------------------------------
CREATE UNIQUE INDEX CODE_UK
    ON bo.MEMBRES(code);

CREATE UNIQUE INDEX MEMBRES_NOM_COMPLET_I
    ON bo.MEMBRES(prenom, nom);

--------------------------------------------------------
--  Index pour la table LIVRES
--------------------------------------------------------
CREATE UNIQUE INDEX LIVRES_ISBN_I
    ON bo.LIVRES(isbn);

--------------------------------------------------------
--  Index pour la table GENRES
--------------------------------------------------------
CREATE UNIQUE INDEX GENRES_NOM_I
    ON bo.GENRES(nom_genre);

/***************** VUES ************************/

CREATE OR REPLACE VIEW Dictionnaire_V AS
SELECT utcol.table_name,
       utcol.column_id,
       utcol.column_name,
       utcol.data_type,
       utcol.data_length,
       utcol.data_precision,
       utcol.data_scale,
       utcol.nullable,
       utcomm.comments AS commentaire_table,
       uccomm.comments AS commentaire_colonne
FROM USER_TAB_COLUMNS utcol
         LEFT JOIN USER_TAB_COMMENTS utcomm
                   ON utcol.table_name = utcomm.table_name
         LEFT JOIN USER_COL_COMMENTS uccomm
                   ON utcol.table_name = uccomm.table_name
                       AND utcol.column_name = uccomm.column_name
ORDER BY utcol.table_name, utcol.column_id
WITH READ ONLY;
/
COMMIT;

/*****************
    CONTRAINTES
******************/

-- Contraintes de format

ALTER TABLE bo.MEMBRES
    ADD CONSTRAINT GENRE_CHK CHECK ( GENRE IN ('M','F','X'));

ALTER TABLE bo.MEMBRES
    ADD CONSTRAINT TELEPHONE_CHK CHECK ( REGEXP_LIKE(TELEPHONE, '\d{3}-\d{3}-\d{4}$'));

ALTER TABLE bo.MEMBRES
    ADD CONSTRAINT CODE_MEMBRE_CHK CHECK ( REGEXP_LIKE(CODE, '[a-zA-Z]{4}\d{8}$'));

ALTER TABLE bo.MEMBRES
    ADD CONSTRAINT PAYS_CHK CHECK ( UPPER(PAYS) IN ('CANADA','ÉTATS-UNIS','MEXIQUE'));

ALTER TABLE bo.SECTIONS
    ADD CONSTRAINT SECTION_CHK CHECK ( ID BETWEEN 0 AND 999);

ALTER TABLE bo.EMPRUNTS
    ADD DATE_RETOUR_PREVU DATE GENERATED ALWAYS AS (DATE_EMPRUNT + INTERVAL '21' DAY) VIRTUAL ;

ALTER TABLE bo.EMPRUNTS
    ADD code_suivi VARCHAR2(25);

ALTER TABLE bo.membres
    ADD montant_amende NUMBER(10,2) DEFAULT 0 NOT NULL


-- Contraintes de clé

ALTER TABLE bo.SECTIONS
    ADD CONSTRAINT SECTIONS_PK PRIMARY KEY (ID);

ALTER TABLE bo.GENRES
    ADD CONSTRAINT GENRES_PK PRIMARY KEY (ID);

ALTER TABLE bo.LIVRES
    ADD CONSTRAINT LIVRES_PK PRIMARY KEY (ID);

ALTER TABLE bo.AUTEURS
    ADD CONSTRAINT AUTEURS_PK PRIMARY KEY (ID);

ALTER TABLE bo.MEMBRES
    ADD CONSTRAINT MEMBRES_PK PRIMARY KEY (ID);

ALTER TABLE bo.EMPRUNTS
    ADD CONSTRAINT EMPRUNTS_PK PRIMARY KEY (ID);

ALTER TABLE bo.LIVRES
    ADD CONSTRAINT LIVRES_FK1 FOREIGN KEY (SECTIONS_ID)
        REFERENCES bo.SECTIONS(ID)
        ENABLE;

ALTER TABLE bo.LIVRES
    ADD CONSTRAINT LIVRES_FK2 FOREIGN KEY (AUTEURS_ID)
        REFERENCES bo.AUTEURS(ID)
        ENABLE;

ALTER TABLE bo.LIVRES
    ADD CONSTRAINT LIVRES_FK3 FOREIGN KEY (GENRES_ID)
        REFERENCES bo.GENRES(ID)
        ENABLE;

ALTER TABLE bo.MEMBRES
    ADD CONSTRAINT CODE_UK UNIQUE (code);

ALTER TABLE bo.EMPRUNTS
    ADD CONSTRAINT EMPRUNTS_FK1 FOREIGN KEY (livres_id)
        REFERENCES bo.LIVRES(ID)
        ON DELETE CASCADE
        ENABLE;

ALTER TABLE bo.EMPRUNTS
    ADD CONSTRAINT EMPRUNTS_FK2 FOREIGN KEY (membres_id)
        REFERENCES bo.MEMBRES(ID)
        ENABLE;